# load data

In [14]:
from sklearn.datasets import fetch_20newsgroups

news = fetch_20newsgroups(subset='all')
print(len(news.data), len(news.target))
print(news.data[0], news.target[0])
print(news.target_names)

18846 18846
From: Mamatha Devineni Ratnam <mr47+@andrew.cmu.edu>
Subject: Pens fans reactions
Organization: Post Office, Carnegie Mellon, Pittsburgh, PA
Lines: 12
NNTP-Posting-Host: po4.andrew.cmu.edu



I am sure some bashers of Pens fans are pretty confused about the lack
of any kind of posts about the recent Pens massacre of the Devils. Actually,
I am  bit puzzled too and a bit relieved. However, I am going to put an end
to non-PIttsburghers' relief with a bit of praise for the Pens. Man, they
are killing those Devils worse than I thought. Jagr just showed you why
he is much better than his regular season stats. He is also a lot
fo fun to watch in the playoffs. Bowman should let JAgr have a lot of
fun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final
regular season game.          PENS RULE!!!

 10
['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardw

# preprocess data

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(news.data, news.target, test_size = 0.25)

# learn data

In [21]:
from sklearn.feature_extraction.text import CountVectorizer, HashingVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

clf_1 = Pipeline([('count_vec', CountVectorizer()), ('mnb', MultinomialNB())])
#clf_2 = Pipeline([('hash_vec', HashingVectorizer(non_negative=True)), ('mnb', MultinomialNB())])
clf_3 = Pipeline([('tfidf_vec', TfidfVectorizer()), ('mnb', MultinomialNB())])
clf_4 = Pipeline([('tfidf_vec_adv', TfidfVectorizer(stop_words='english')), ('mnb', MultinomialNB())]) #精细筛选
clf_5 = Pipeline([('tfidf_vec_adv', TfidfVectorizer(stop_words='english')), ('mnb', MultinomialNB(alpha=0.01))]) #平滑参数

clf_1.fit(X_train, y_train)
#clf_2.fit(X_train, y_train)
clf_3.fit(X_train, y_train)
clf_4.fit(X_train, y_train)
clf_5.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf_vec_adv',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words='english', strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('mnb',
                 MultinomialNB(alpha=0.01, class_prior=None, fit_prior=True))],
         verbose=False)

# predict data

In [23]:
from sklearn import metrics

clfs = [clf_1, clf_3, clf_4, clf_5]
for clf in clfs:
    y_train_predict = clf.predict(X_train)
    y_test_predict = clf.predict(X_test)
    print(metrics.accuracy_score(y_train, y_train_predict), metrics.accuracy_score(y_test, y_test_predict))

0.9243667751521155 0.8471986417657046
0.9242252723928117 0.8484719864176571
0.9505447856233197 0.8783955857385399
0.9955426630819301 0.9161714770797963


# cross validation score

In [25]:
from sklearn.model_selection import cross_val_score
import numpy as np

for clf in clfs:
    scores = cross_val_score(clf, X_train, y_train)
    print(scores)
    print(np.mean(scores), np.std(scores))

[0.83728334 0.84612664 0.84329678 0.82737885 0.83864119]
0.8385453584145001 0.006424089721321395
[0.83586841 0.8302087  0.83940573 0.83303856 0.83793347]
0.835290975130872 0.003321154617218102
[0.86805801 0.8800849  0.87619385 0.86664308 0.87508846]
0.8732136603087556 0.005086520249792133
[0.90555359 0.91439689 0.91050584 0.90307747 0.91401274]
0.9095093040494413 0.004520589909437558
