In [1]:
import numpy as np

In [2]:
array = np.array([[1, 2, 3],
                  [2, 3, 4]])

In [3]:
print(array)

[[1 2 3]
 [2 3 4]]


In [4]:
print('numbrt of dimension:', array.ndim)

numbrt of dimension: 2


In [5]:
print('shape:', array.shape)

shape: (2, 3)


In [6]:
print('size:', array.size)

size: 6


In [7]:
import numpy as np

In [8]:
a = np.array([[1, 23, 4],
             [2, 32, 4]])
print(a)

[[ 1 23  4]
 [ 2 32  4]]


In [9]:
a = np.zeros((3, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
a = np.ones((3, 4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
a = np.empty((3, 4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
a = np.arange(12).reshape((3, 4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
a = np.linspace(1, 10, 6).reshape((2, 3))
print(a)

[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]


In [14]:
a = np.array([10, 20, 30, 40])

In [15]:
b = np.arange(4)
print(b)

[0 1 2 3]


In [16]:
c = 10 * np.sin(a)
print(c)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [17]:
print(b == 3)

[False False False  True]


In [18]:
a = np.array([[1, 1],
             [0, 1]])
b = np.arange(4).reshape((2, 2))

In [19]:
a * b

array([[0, 1],
       [0, 3]])

In [20]:
np.dot(a, b)

array([[2, 4],
       [2, 3]])

In [21]:
a.dot(b)

array([[2, 4],
       [2, 3]])

In [22]:
a = np.random.random((2, 4))

In [23]:
print(a)

[[0.11723937 0.64717384 0.62117226 0.82839744]
 [0.09860991 0.66059598 0.52104338 0.14042766]]


In [24]:
np.sum(a)

3.6346598449390695

In [25]:
np.min(a)

0.09860991461101332

In [26]:
np.max(a)

0.8283974390100829

In [27]:
a.min

<function ndarray.min>

In [28]:
a.min()

0.09860991461101332

In [29]:
a.sum(axis = 0)

array([0.21584929, 1.30776982, 1.14221564, 0.9688251 ])

In [30]:
A = np.arange(2, 14).reshape((3, 4))

In [31]:
print(A)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [32]:
np.argmin(A)

0

In [33]:
A.argmin()

0

In [34]:
A.argmax()

11

In [35]:
A.mean()

7.5

In [36]:
A.mean(axis = 1)

array([ 3.5,  7.5, 11.5])

In [37]:
A.average()

AttributeError: 'numpy.ndarray' object has no attribute 'average'

In [ ]:
A.median()

In [ ]:
print(np.median(A))

In [ ]:
np.cumsum(A)

In [ ]:
np.diff(A)

In [ ]:
np.nonzero(A)

In [ ]:
np.sort(A)

In [ ]:
A.transpose()

In [ ]:
A.T.dot(A)

In [ ]:
np.clip(A, 9, 5)

In [42]:
A = np.arange(3, 15).reshape((3, 4))

In [43]:
A

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [45]:
A[2]

array([11, 12, 13, 14])

In [47]:
for row in A:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [49]:
for column in A.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [50]:
for item in A.flat:
    print(item)

3
4
5
6
7
8
9
10
11
12
13
14


In [51]:
A.flatten()

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [52]:
A = np.array([1, 1, 1])

In [53]:
B = np.array([2, 2, 2])

In [54]:
np.vstack((A, B))

array([[1, 1, 1],
       [2, 2, 2]])

In [55]:
np.hstack((A, B))

array([1, 1, 1, 2, 2, 2])

In [56]:
A

array([1, 1, 1])

In [57]:
A[np.newaxis, :]

array([[1, 1, 1]])

In [58]:
A[:, np.newaxis]

array([[1],
       [1],
       [1]])

In [60]:
np.concatanate(A, A)

AttributeError: module 'numpy' has no attribute 'concatanate'

In [61]:
A = np.arange(12).reshape((3, 4))

In [66]:
np.array_split(A, 3, axis = 1)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [67]:
np.vsplit(A, 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [68]:
a = b = c = d = np.arange(4)

In [69]:
a[0] = 11

In [70]:
a

array([11,  1,  2,  3])

In [71]:
b

array([11,  1,  2,  3])

In [72]:
d 

array([11,  1,  2,  3])

In [73]:
b = a.copy()

In [74]:
b

array([11,  1,  2,  3])

In [75]:
a[0] = 12

In [76]:
b

array([11,  1,  2,  3])

In [80]:
b = copy.deepcopy(a)

NameError: name 'copy' is not defined